### ISSUE TITLE
Operations plugin doesn't work with unnamed queries

### ISSUE THREAD

**Issue by ertrzyiks** [zhouzi/graphql-codegen-factories#26]
Using the config like
```yml
./src/:
    preset: near-operation-file
    presetConfig:
      extension: .generated.ts
      baseTypesPath: types.ts
    plugins:
      - typescript-operations
      - graphql-codegen-factories/operations
```

and the operation without a name
```gql
{ field }
```

the generated code refers to not existing type `Query`
```
export type Unnamed_1_Query = ....

export function createQueryMock(props: Partial<Query>): Query {
```

It only works with the named query

```gql
query getField { field }
```

Tested with https://github.com/yummy-recipes/yummy/pull/58
