### ISSUE TITLE
Operations plugin generates a single item for array types

### ISSUE THREAD

**Issue by ertrzyiks** [zhouzi/graphql-codegen-factories#27]
Using the config like
```yml
./src/:
    preset: near-operation-file
    presetConfig:
      extension: .generated.ts
      baseTypesPath: types.ts
    plugins:
      - typescript-operations
      - graphql-codegen-factories/operations
```

When a selection references an array, the factory returns a single element.

When the 
```gql
query { 
  allStrapiRecipe {
    edges { # this is an array
      node {
        ...fields
      }
    }
  }
}
```
Expected
```js
{
  allStrapiRecipe: {
    __typename: 'StrapiRecipeConnection',
    edges: [{
      __typename: 'StrapiRecipeEdge',
      node: {
        __typename: 'StrapiRecipe',
      },
    }]
  },
}  
```

Actual
```js
{
  allStrapiRecipe: {
    __typename: 'StrapiRecipeConnection',
    edges: {
      __typename: 'StrapiRecipeEdge',
      node: {
        __typename: 'StrapiRecipe',
      },
    },
  }
}  
```

Tested with https://github.com/yummy-recipes/yummy/pull/58
