### ISSUE TITLE
Operations plugin generates [object Object] for fragments

### ISSUE THREAD

**Issue by ertrzyiks** [zhouzi/graphql-codegen-factories#28]
Using the config like
```yml
./src/:
    preset: near-operation-file
    presetConfig:
      extension: .generated.ts
      baseTypesPath: types.ts
    plugins:
      - typescript-operations
      - graphql-codegen-factories/operations
```

when a query file includes a fragment definition, the output file includes `[object Object]` line.

Similar to #23

Tested with https://github.com/yummy-recipes/yummy/pull/58
