### ISSUE TITLE
Operations plugin does not include fields from fragments

### ISSUE THREAD

**Issue by ertrzyiks** [zhouzi/graphql-codegen-factories#30]
Hey, thanks a lot for the latest updates!

Here is my config
```yml
overwrite: true
schema: "graphql/schema.json"
documents:
  - "src/**/*.{js,jsx}"
  - ./node_modules/gatsby*/!(node_modules)/**/*.js
generates:
  ./src/types.ts:
    plugins:
      - typescript
  ./src/:
    preset: near-operation-file
    presetConfig:
      extension: .generated.ts
      baseTypesPath: types.ts
    plugins:
      - typescript-operations
      - graphql-codegen-factories/operations
```

and I installed
```
"graphql-codegen-factories": "^1.0.0-beta.2",
```

The queries that are include fragments generate the function that misses the fields from the fragment.

```gql
#import "../fragments/myData.gql"
query GetMyData {
  data {
    id
    ...MyData
  }
}
```

It generates an object with just `data: { id }` not matter what is selected by the fragment.
