### ISSUE TITLE
Omit optional properties by default?

### ISSUE THREAD

**Issue by zhouzi** [zhouzi/graphql-codegen-factories#65]
From https://github.com/zhouzi/graphql-codegen-factories/pull/63#pullrequestreview-1233353880:

> What do you think about not adding the optional properties at all by default? By default the TypeScript plugins set the properties to title?: Maybe<string> and have an option "avoidOptionals" to remove the ?. So I feel like not adding the optional properties unless "avoidOptionals" is set to true would be closer to the TypeScript plugins' defaults and avoid issues similar to the one you faced.

**Comment by jongbelegen** [comment]
I think this idea makes sense.

Note that avoidOptionals can be used as a bool or AvoidOptionalsConfig.
For example, my config looks like this:

```
      avoidOptionals:
        field: true
        inputValue: false
        object: true
        defaultValue: true
```
